#!/bin/bash

# Description:
#   This script is main scipt to manage EHSystem
#
# Arguments:
#   $1 - command to run
#
# Possible values:
#   update - pulls the current repository branch, and start updates scipts
# 
# Flags:
#   -h - show help message
#
# Example of usage:
#   EHSystem update

readonly SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

POSITIONAL_ARGS=()

# Read commands and options
while [[ $# -gt 0 ]];
do
  case $1 in
    -h|--help)
      echo "Help:
update - updates EHSystem

Options:
-h shows this message"
      exit 1
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *) POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argunent
      ;;
  esac
done

# Restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

# Handle update command
if [ $1 == "update" ];
then
  echo "Update command launched"
  git -C ${SCRIPT_DIR} pull
  source ${SCRIPT_DIR}/update.sh
fi
